### ISSUE TITLE
$1500

### ISSUE THREAD

**Issue by kazmithub** [IKGame/coinprice#2]
The error message "ConnectionRefusedError: [Errno 61] Connection refused" means that the Python script tried to connect to a remote server, but the server refused the connection. This could've been caused by:

- The remote server may be down or offline.
- The remote server may be blocking connections from specific IP addresses.
- There may be a firewall between your computer and the remote server that is blocking the connection.
In this case, the error is happening in the models/__init__.py file. The line of code that is causing the error is this:

A.connect((r,443))

A variable: It is an instance of the requests library's Session class. The connect() method on the Session class tries to connect to a remote server. The connect() method takes two arguments: the hostname of the remote server and the port number of the remote server. In this case, the hostname is the variable r and the port number is 443.
R Variable: It is defined in the models.exchange.Granularity class. The Granularity class is used to represent different time granularities for cryptocurrency prices. The r variable is assigned the value of the hostname of the CoinMarketCap API.

The CoinMarketCap API is a RESTful API that provides access to cryptocurrency data. The API is hosted on a remote server. When the connect() method is called, it tries to connect to the CoinMarketCap API server. However, the connection is refused. This is because the CoinMarketCap API server is not accepting connections from your IP address.

There are a few things that can be done here:

We can try connecting to the CoinMarketCap API server from a different IP address. We can use a VPN as well.
You can use a different API to get cryptocurrency data. There are many other APIs that provide access to cryptocurrency data.

**Comment by andrey0490** [comment]
Solved
